### PR TITLE
Use Babel 6 and let Webpack handle ES2015 compilation.

### PR DESCRIPTION
**Pull request by epsitec**
There were several changes in Babel 6 which motivated me to upgrade the sample project. While doing this, I decided to get rid of Wallaby.js `preprocessors` in favor of letting Webpack handle the compilation.

### CODE REVIEW

**Comment by epsitec** [comment]
Any idea why the error messages do not show up in the source window? Has this anything to do with the fact that Webpack is used?

wallaby-2

**Comment by ArtemGovorov** [comment]
@epsitec we actually [recommend using wallaby babel compiler](http://wallabyjs.com/docs/integration/webpack.html#loaders-vs-preprocessors-compilers) instead of Webpack babel loader, because it's faster and doesn't require source map configuration (that may be the reason why the inline message is missing).

Having said that, I think updating the sample to Babel 6 is a good idea. Would you be ok changing the PR to use compilers instead?

``` JavaScript
var babel = require('babel-core');
...
compilers: {
      '**/*.js': wallaby.compilers.babel({ babel: babel, presets: ['es2015'] }),
    }
```

**Comment by epsitec** [comment]
@ArtemGovorov ok, I'll update my PR in order to use of the _wallaby babel compiler_.

However, in my case, I was experimenting with **Webpack loaders**, so that I can transform the source code before it is being fed into babel. I don't see how I could plug the Webpack loaders into Wallaby.js without using the Webpack babel loaders.

I need to apply a custom loader (working on `*.js` source code) before calling babel. Is this possible with Wallaby.js?

**Comment by epsitec** [comment]
@ArtemGovorov you were right: using the _wallaby babel compiler_ restored the inline display of the error messages.

**Comment by ArtemGovorov** [comment]
> so that I can transform the source code before it is being fed into babel.

If that's important that the source code is transformed _before_ babel, you may still use webpack babel loader. Just make sure to pass [correct source map settings](http://wallabyjs.com/docs/integration/webpack.html#source-maps-and-devtool-option) so that wallaby knows how to map error stacks (required to display inline messages), etc. BTW, the same applies to any other code transformers - they need to be able to generate proper source maps so that other tools, for example debuggers (and wallaby stack mapping) could work.

**Comment by epsitec** [comment]
Just for the record, using Webpack babel loader with correct source mapping requires this configuration:

``` js
var webpackPostprocessor = wallabyWebpack({
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel?presets[]=es2015'
      }
    ]
  },
  devtool: 'source-map'
});
```

**Comment by ArtemGovorov** [comment]
@epsitec Thanks! Have added you sample to the corresponding [wallaby docs section](http://wallabyjs.com/docs/integration/webpack.html#source-maps-and-devtool-option)

**Pull request merged**
